steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/web/Dockerfile', '-t', 'us-central1-docker.pkg.dev/tar-012f42959395/apps/pdf-checker-web:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/tar-012f42959395/apps/pdf-checker-web:latest'
